/**
 * Turns src/lib/catalog.generated.json into supabase/seed.sql.
 *
 *   node scripts/generate-seed.mjs
 *
 * Idempotent: every row is an upsert keyed on the barcode, so re-running after
 * a fresh `npm run import:catalog` updates the catalog without touching any
 * ratings that point at it.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const catalog = JSON.parse(
  readFileSync(join(ROOT, "src", "lib", "catalog.generated.json"), "utf8"),
);

/** Single-quote a value for SQL, or emit NULL. */
const q = (v) =>
  v === null || v === undefined ? "NULL" : `'${String(v).replace(/'/g, "''")}'`;
const n = (v) => (v === null || v === undefined ? "NULL" : String(v));

const rows = catalog.drinks.map((d) =>
  [
    q(d.id),
    q(d.barcode),
    q(d.name),
    q(d.brand),
    q(d.sub),
    n(d.ml),
    n(d.caf),
    n(d.sug),
    n(d.cal),
    n(d.sweet),
    n(d.nuke),
    q(d.color),
    q(d.imageUrl),
    q(d.imageSmallUrl),
    q(d.source),
    d.us ? "true" : "false",
    "'live'",
  ].join(", "),
);

const sql = `-- GENERATED by scripts/generate-seed.mjs — do not edit by hand.
--
-- Catalog: ${catalog.count} cans from ${catalog.generatedFrom}.
-- Data licence:  ${catalog.dataLicense}
-- Image licence: ${catalog.imageLicense}
-- Attribution:   ${catalog.attributionUrl}  (see ATTRIBUTION.md)
--
-- Safe to re-run: upserts on the primary key, leaving ratings intact.

insert into public.drinks (
  id, barcode, name, brand, sub, ml, caf, sug, cal,
  sweet, nuke, color, image_url, image_small_url, source, us, status
) values
${rows.map((r) => `  (${r})`).join(",\n")}
on conflict (id) do update set
  name            = excluded.name,
  brand           = excluded.brand,
  sub             = excluded.sub,
  ml              = excluded.ml,
  caf             = excluded.caf,
  sug             = excluded.sug,
  cal             = excluded.cal,
  sweet           = excluded.sweet,
  nuke            = excluded.nuke,
  color           = excluded.color,
  image_url       = excluded.image_url,
  image_small_url = excluded.image_small_url,
  source          = excluded.source,
  us              = excluded.us,
  -- never demote a live can, and never silently revive a rejected one
  status          = case
                      when public.drinks.status = 'rejected' then 'rejected'
                      else 'live'
                    end;
`;

mkdirSync(join(ROOT, "supabase"), { recursive: true });
const out = join(ROOT, "supabase", "seed.sql");
writeFileSync(out, sql);
console.log(`${catalog.count} cans -> ${out}`);
